# Generated by Django 3.2.8 on 2021-10-12 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemadmin', '0001_initial'),
        ('doctor', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('phone', models.CharField(max_length=100)),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.baseuser')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.baseuser')),
                ('clinicid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemadmin.clinic')),
                ('specialty', models.ManyToManyField(to='doctor.Specialty')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicAdmin',
            fields=[
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.baseuser')),
                ('clinicid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemadmin.clinic')),
            ],
        ),
    ]
