# Generated by Django 3.2.8 on 2021-10-15 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemadmin', '0008_auto_20211015_1157'),
        ('clinicadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('clinicid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemadmin.clinic')),
            ],
        ),
    ]
