# Generated by Django 3.2.8 on 2021-10-15 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211013_0221'),
        ('clinicadmin', '0002_publicholiday_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekdaystart', models.TimeField(null=True)),
                ('weekdayend', models.TimeField(null=True)),
                ('satstart', models.TimeField(null=True)),
                ('satend', models.TimeField(null=True)),
                ('sunstart', models.TimeField(null=True)),
                ('sunend', models.TimeField(null=True)),
                ('phstart', models.TimeField(null=True)),
                ('phend', models.TimeField(null=True)),
                ('doctorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctor')),
            ],
        ),
    ]
