# Generated by Django 3.2.8 on 2021-10-15 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211013_0221'),
        ('clinicadmin', '0003_doctorschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctorid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.doctor'),
        ),
    ]
