# Generated by Django 3.2.8 on 2021-10-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicadmin', '0006_appointmenttype_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]
