# Generated by Django 3.2.8 on 2021-10-25 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicadmin', '0008_auto_20211024_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='datetimeend',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 10, 11, 40, 355273)),
        ),
    ]
