# Generated by Django 3.2.8 on 2021-11-03 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicadmin', '0011_alter_slot_datetimeend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='datetimeend',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 1, 26, 50, 727603)),
        ),
    ]
