# Generated by Django 3.2.8 on 2021-10-19 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicadmin', '0006_appointmenttype_slot'),
        ('systemadmin', '0008_auto_20211015_1157'),
        ('users', '0003_auto_20211013_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('confirm', models.BooleanField(default=False)),
                ('clinicid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemadmin.clinic')),
                ('doctorid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.doctor')),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicadmin.room')),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicadmin.slot')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicadmin.appointmenttype')),
            ],
        ),
    ]
