# Generated by Django 3.2.8 on 2021-10-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211013_0221'),
        ('clinicadmin', '0006_appointmenttype_slot'),
        ('systemadmin', '0008_auto_20211015_1157'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Appointment',
        ),
    ]
