# Generated by Django 3.2.8 on 2021-10-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_appointment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
