# Generated by Django 3.2.8 on 2021-10-22 05:33

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211013_0221'),
        ('patient', '0008_auto_20211022_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctorid',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='clinicid', chained_model_field='clinicid', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.doctor'),
        ),
    ]
