# Generated by Django 3.2.8 on 2021-10-22 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211013_0221'),
        ('patient', '0009_alter_appointment_doctorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctorid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.doctor'),
        ),
    ]
