# Generated by Django 3.2.8 on 2021-10-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_alter_appointment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='canconfirm',
            field=models.BooleanField(default=False),
        ),
    ]
