# Generated by Django 3.2.8 on 2021-10-12 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekdaystart', models.TimeField()),
                ('weekdayend', models.TimeField()),
                ('satstart', models.TimeField()),
                ('satend', models.TimeField()),
                ('sunstart', models.TimeField()),
                ('sunend', models.TimeField()),
                ('phstart', models.TimeField()),
                ('phend', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('apptinterval', models.IntegerField()),
                ('doctorinterval', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/clinics')),
                ('location', models.CharField(choices=[('north', 'NORTH'), ('south', 'SOUTH'), ('central', 'CENTRAL'), ('east', 'EAST'), ('west', 'WEST')], default='central', max_length=100)),
                ('openinghours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemadmin.openinghours')),
            ],
        ),
    ]
