# Generated by Django 3.2.8 on 2021-10-12 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemadmin', '0003_auto_20211012_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='phend',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='phstart',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='satend',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='satstart',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='sunend',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='sunstart',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='weekdayend',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='weekdaystart',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
