# Generated by Django 3.2.8 on 2021-10-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemadmin', '0004_auto_20211012_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='location',
            field=models.CharField(choices=[('North', 'North'), ('South', 'South'), ('Central', 'Central'), ('East', 'East'), ('West', 'West')], default='central', max_length=100),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Specialist', 'Specialist')], default='normal', max_length=100),
        ),
    ]
