# Generated by Django 3.2.8 on 2021-10-13 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemadmin', '0005_auto_20211013_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('clinicid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemadmin.clinic')),
            ],
        ),
    ]
