# Generated by Django 3.2.8 on 2021-10-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemadmin', '0006_adminrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/clinics'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='phend',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='phstart',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='satend',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='satstart',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='sunend',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='sunstart',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='weekdayend',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='weekdaystart',
            field=models.TimeField(blank=True),
        ),
    ]
