# Generated by Django 3.2.8 on 2021-10-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemadmin', '0007_auto_20211014_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='phend',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='phstart',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='satend',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='satstart',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='sunend',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='sunstart',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='weekdayend',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='weekdaystart',
            field=models.TimeField(null=True),
        ),
    ]
